name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  VERSION_LABEL: v-${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Zip the application
      run: |
        zip -r app.zip . -x "*.git*" "*.github*" "tmp/*" "log/*"

    - name: Upload ZIP to S3
      run: |
        aws s3 cp app.zip s3://${{ secrets.S3_BUCKET_NAME }}/app-${{ env.VERSION_LABEL }}.zip

    - name: Create Application Version
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name "${{ secrets.APPLICATION_NAME }}" \
          --version-label "${{ env.VERSION_LABEL }}" \
          --source-bundle S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=app-${{ env.VERSION_LABEL }}.zip

    - name: Wait for version to register
      run: sleep 60

    - name: Update Environment to New Version
      run: |
        aws elasticbeanstalk update-environment \
          --environment-name "${{ secrets.ENVIRONMENT_NAME }}" \
          --version-label "${{ env.VERSION_LABEL }}"

    - name:  Deployment Complete
      run: echo "Successfully deployed version $VERSION_LABEL"
