name: Deploy to Elastic Beanstalk 

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Application
        run: zip -r app.zip . -x '*.git*'

      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://${{ secrets.S3_BUCKET_NAME }}/app-${{ github.run_number }}.zip

      - name: Create Elastic Beanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.APPLICATION_NAME }}" \
            --version-label "v-${{ github.run_number }}" \
            --source-bundle S3Bucket="${{ secrets.S3_BUCKET_NAME }}",S3Key="app-${{ github.run_number }}.zip"

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.ENVIRONMENT_NAME }}" \
            --version-label "v-${{ github.run_number }}"
